Task1
SphericalPotatoInVacuum/hash_map pull request #1
Opened 2020-03-02 09:40 UTC by SphericalPotatoInVacuum

Tried to make all variables follow the google code style guide, removed copy-paste code, removed redundant ifs, moved the minimum map size to a constant, changed access level of an inner-used method to private.

2020-03-07 22:17 UTC, feldsherov requested changes

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +    data_.resize(16);
16 в константу

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +  void insert_existing(iterator iter) {
явно private

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +  const_iterator find(KeyType key) const {
Есть способ убрать копипасту const и не const методов здесь. Сделай это.

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +  std::list<std::pair<const KeyType, ValueType>> pdata_;
pdata так себе имечко. Как и data

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == key)) {
Давай for?

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == key)) {
И тут for

2020-03-07 22:17 UTC, feldsherov commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == element.first)) {
find

2020-03-08 00:14 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +    data_.resize(16);
Согласен, не запушил последний коммит, в нём была в константе, простите.

2020-03-08 00:15 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +  void insert_existing(iterator iter) {
Аналогично с константой

2020-03-08 00:15 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +  const_iterator find(KeyType key) const {
Использовал static_cast

2020-03-08 00:16 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +  std::list<std::pair<const KeyType, ValueType>> pdata_;
Подумал и кроме как buckets вместо data и dict вместо pdata лучше придумать ничего не смог

2020-03-08 00:16 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == key)) {
Лучше! find_if

2020-03-08 00:16 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == key)) {
И тут find_if

2020-03-08 00:18 UTC, SphericalPotatoInVacuum commented on hash_map.h
> +    while (it != data_[index].end() && !((*it)->first == element.first)) {
Переместил код в отдельную приватную функцию find_iterator которая возвращает индекс ведра и итератор на элемент этого ведра. Если не нашла, то возвращает итератор на конец

2020-03-15 10:28 UTC, feldsherov approved these changes
ок

2020-03-15 10:28 UTC, feldsherov commented on .gitignore
> +.vscode
https://habr.com/en/post/202696/

В pr должен быть только код.

2020-03-15 22:54 UTC, closed without merging